### ISSUE TITLE
0.13.0 doesn't work on private network

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neo-exporter#165]
while all four (mainnet, testnet, mainnet fschain, testnet fschain) work fine, private network does not:
```
can't initialize netmap monitor: can't create side chain neo-go client: init Neo RPC client: failed to get network magic: HTTP 415/Unsupported Media Type
```

config.yaml:
```
chain:
  fschain: true
  rpc:
    dial_timeout: 15s
    endpoint:
    - https://a1.tld
    - https://a2.tld
    - https://a3.tld
    - https://a4.tld
    - https://a5.tld
    - https://a6.tld
    - https://a7.tld
logger:
  level: info
metrics:
  endpoint: 127.0.0.1:16516
  interval: 15s
```
