### ISSUE TITLE
Remove netmap v1 logic

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-exporter#166]
## Current Behavior
![Image](https://github.com/user-attachments/assets/a7dbb2cb-057a-4ec1-9018-00747709a966)
Which is based on exporter data. But in reality
```
e$ ./bin/neofs-cli netmap snapshot -r grpcs://st1.storage.fs.neo.org:8082
Epoch: 30823
Node 1: 02d251dc43170ced47a82379937977300832d882131e22b7b753832a8184106289 ONLINE /dns4/st3.storage.fs.neo.org/tcp/8080 
        Capacity: 22176
        Price: 10
        Continent: Europe
        SubDivCode: 18
        Deployed: NSPCC
        Location: Tuusula
        UN-LOCODE: FI TUU
        CountryCode: FI
        Country: Finland
        Version: 0.45.2
        SubDiv: Uusimaa
Node 2: 02f16c467682074c3e60532f1200761bfba88c5a77d1702b4608216ec7afb02bb1 ONLINE /dns4/st2.storage.fs.neo.org/tcp/8080 
        Country: Canada
        Location: Beauharnois
        Deployed: NSPCC
        SubDiv: Quebec
        Version: 0.45.2
        Capacity: 22175
        Price: 10
        SubDivCode: QC
        UN-LOCODE: CA BHA
        Continent: North America
        CountryCode: CA
Node 3: 0304935132e390bb119eded3ca56cc27292eaa8942970d632a82abed349f0aa0a1 ONLINE /dns4/st4.storage.fs.neo.org/tcp/8080 
        SubDivCode: 67
        CountryCode: FR
        SubDiv: Bas-Rhin
        Capacity: 14665
        UN-LOCODE: FR SXB
        Price: 10
        Deployed: NSPCC
        Country: France
        Location: Strasbourg
        Version: 0.45.2
        Continent: Europe
Node 4: 03aeff8a19f0202090afb0916b1c00b432321be7e8623a06c9b9b5db8ee5c053a4 ONLINE /dns4/st1.storage.fs.neo.org/tcp/8080 
        Location: Falkenstein
        SubDiv: Sachsen
        UN-LOCODE: DE FKS
        Country: Germany
        Capacity: 22176
        Continent: Europe
        SubDivCode: SN
        Version: 0.45.2
        Price: 10
        Deployed: NSPCC
        CountryCode: DE
```
we have four nodes. And v1 netmap has three nodes, so it looks like it's related to v1/v2 logic.

## Expected Behavior
Correct netmap exported.

## Possible Solution
For simplicity let's just drop v1 map support, we no longer need it.

## Steps to Reproduce
Export mainnet data, config is known to @532910.

## Context
https://github.com/nspcc-dev/status-fs-neo-org/issues/115

## Regression
Almost.

## Your Environment
* Version of the product used: 0.13.0

**Comment by roman-khimov** [comment]
```
chain:
  fschain: true
  rpc:
    dial_timeout: 15s
    endpoint:
    - https://rpc1.morph.fs.neo.org
    - https://rpc2.morph.fs.neo.org
    - https://rpc3.morph.fs.neo.org
    - https://rpc4.morph.fs.neo.org
    - https://rpc5.morph.fs.neo.org
    - https://rpc6.morph.fs.neo.org
    - https://rpc7.morph.fs.neo.org
logger:
  level: info
metrics:
  endpoint: 127.0.0.1:16513
  interval: 15s
```
